### ISSUE TITLE
[Tracking] Devnet 5

### ISSUE THREAD

**Issue by onbjerg** [alloy-rs/alloy#1711]
### Component

other

### Describe the feature you would like

- [x] https://github.com/alloy-rs/alloy/issues/1710
- [x] https://github.com/alloy-rs/alloy/issues/1709
- [x] https://github.com/alloy-rs/alloy/issues/1712
- [x] https://github.com/alloy-rs/alloy/issues/1829
- [x] https://github.com/alloy-rs/alloy/issues/1830
- [x] https://github.com/alloy-rs/alloy/issues/1831
- [x] https://github.com/alloy-rs/alloy/issues/1832
- [x] https://github.com/alloy-rs/alloy/issues/1833
- [x] https://github.com/alloy-rs/alloy/issues/1837
